import type { Delivery, TeamMemberCapacity } from "./types";

const minutesAgo = (m: number) => new Date(Date.now() - m * 60_000).toISOString();
const hoursFromNow = (h: number) => new Date(Date.now() + h * 3_600_000).toISOString();

export const mockDeliveries: Delivery[] = [
  {
    id: "d1",
    clientName: "Cliente X",
    projectName: "Campanha Agosto",
    deliveryType: "Carrossel",
    quantity: 3,
    title: "Carrossel — Lançamento linha nova",
    assigneeName: "Maria",
    status: "em_producao",
    priority: "alta",
    dueAt: hoursFromNow(6),
    estimateMinutes: 120,
    effortPoints: 2,
    adjustmentCount: 0,
    activeSessionStartedAt: minutesAgo(44),
    activeSecondsAccumulated: 0,
  },
  {
    id: "d2",
    clientName: "Cliente Y",
    projectName: "Lançamento",
    deliveryType: "Post estático",
    quantity: 1,
    title: "Post estático — anúncio de lançamento",
    assigneeName: "João",
    status: "aguardando_revisao",
    priority: "normal",
    estimateMinutes: 70,
    effortPoints: 1,
    adjustmentCount: 0,
    activeSecondsAccumulated: 68 * 60,
  },
  {
    id: "d3",
    clientName: "Cliente Z",
    projectName: "Institucional",
    deliveryType: "Landing page",
    quantity: 1,
    title: "Landing page — Institucional (ajuste 2)",
    assigneeName: "João",
    status: "em_ajuste",
    priority: "urgente",
    dueAt: hoursFromNow(-2),
    estimateMinutes: 840,
    effortPoints: 12,
    adjustmentCount: 2,
    activeSecondsAccumulated: 620 * 60,
  },
  {
    id: "d4",
    clientName: "Rogério",
    deliveryType: "Criativo de tráfego",
    quantity: 3,
    title: "Criativo campanha A",
    assigneeName: "Maria",
    status: "criada",
    priority: "normal",
    dueAt: hoursFromNow(48),
    estimateMinutes: 40,
    effortPoints: 1,
    adjustmentCount: 0,
    activeSecondsAccumulated: 0,
  },
  {
    id: "d5",
    clientName: "Cliente W",
    deliveryType: "Reel",
    quantity: 1,
    title: "Reel — bastidores",
    assigneeName: "João",
    status: "bloqueada",
    priority: "normal",
    notes: "Aguardando material bruto do cliente",
    estimateMinutes: 150,
    effortPoints: 3,
    adjustmentCount: 0,
    activeSecondsAccumulated: 30 * 60,
  },
  {
    id: "d6",
    clientName: "Cliente X",
    deliveryType: "Story ou pacote de stories",
    quantity: 5,
    title: "Pacote de stories — semana",
    assigneeName: "Maria",
    status: "entregue",
    priority: "baixa",
    estimateMinutes: 60,
    effortPoints: 1,
    adjustmentCount: 0,
    activeSecondsAccumulated: 55 * 60,
  },
];

export const mockCapacity: TeamMemberCapacity[] = [
  {
    userId: "u1",
    name: "Maria",
    weeklyCapacityHours: 28,
    weeklyCapacityPoints: 22,
    committedHours: 19,
    committedPoints: 15,
  },
  {
    userId: "u2",
    name: "João",
    weeklyCapacityHours: 28,
    weeklyCapacityPoints: 20,
    committedHours: 24,
    committedPoints: 18,
  },
];
